name: Check and Test

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  pr_check:
    name: PR Check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.12.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check And Test
        run: |
          yarn --frozen-lockfile
          yarn eslint 'src/**'
          yarn test:ci

  finish:
    needs: pr_check
    runs-on: ubuntu-latest
    steps:
      - name: Publish Test Coverage - Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.COVERALL_TOKEN }}
          parallel-finished: true
