name: Check and Test

on: ["push", "pull_request"]

jobs:
  pr_check:
    name: PR Check
    runs-on: ubuntu-latest
    env:
      COVERALLS_SERVICE_NAME: CleanArchCoverage
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      COVERALLS_GIT_BRANCH: main

    strategy:
      matrix:
        node-version: [18.12.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Test and publish to Coveralls
        run: |
          yarn --frozen-lockfile
          yarn eslint 'src/**'
          yarn test:coveralls
